name: digi_notes_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.12.2
  connectivity_plus: ^5.0.1
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  firebase_database: ^10.3.3
  firebase_messaging: ^14.7.4
  firebase_storage: ^11.4.1
  flutter:
    sdk: flutter
  flutter_downloader: ^1.11.4
  flutter_local_notifications: ^16.1.0
  flutter_native_splash: ^2.3.1
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  google_mobile_ads: ^3.0.0
  google_sign_in: ^6.1.6
  path_provider: ^2.1.1
  photo_view: ^0.14.0
  provider: ^6.0.5
  share_plus: ^7.2.1
  syncfusion_flutter_pdfviewer: ^23.1.44
  url_launcher: ^6.1.14
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.gif
    - assets/images/
    - assets/icons/
    - assets/svg/
