name: digi_notes_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  firebase_database: ^10.3.3
  firebase_storage: ^11.4.1
  flutter:
    sdk: flutter
  flutter_downloader: ^1.11.4
  flutter_native_splash: ^2.3.1
  google_sign_in: ^6.1.5
  path_provider: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^23.1.44
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.gif
    - assets/images/
    - assets/icons/
